### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Garam1207** [miyo6032/MaelstromMod#24]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 8/22/20 12:24 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at com.barribob.MaelstromMod.entity.projectile.EntityHealerOrb.bulletHit(EntityHealerOrb.java:288)
	at com.barribob.MaelstromMod.entity.projectile.EntityHealerOrb.func_70071_h_(EntityHealerOrb.java:201)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.barribob.MaelstromMod.entity.projectile.EntityHealerOrb.bulletHit(EntityHealerOrb.java:288)
	at com.barribob.MaelstromMod.entity.projectile.EntityHealerOrb.func_70071_h_(EntityHealerOrb.java:201)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)

-- Entity being ticked --
Details:
	Entity Type: mm:healer_orb (com.barribob.MaelstromMod.entity.projectile.EntityHealerOrb)
	Entity ID: 723
	Entity Name: entity.healer_orb.name
	Entity's Exact location: 326.26, 29.27, 283.80
	Entity's Block location: World: (326,29,283), Chunk: (at 6,1,11 in 20,17; contains blocks 320,0,272 to 335,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.30
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: 새로운 세계
	All players: 1 total; [EntityPlayerMP['Garam1207'/716, l='새로운 세계', x=327.70, y=10.00, z=287.50]]
	Chunk stats: ServerChunkCache: 181 Drop: 0
	Level seed: -628065721898659222
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 454834928 bytes (433 MB) / 939524096 bytes (896 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version      | Source                                    | Signature                                |
	|:--------- |:------------------- |:------------ |:----------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2       | minecraft.jar                             | None                                     |
	| UCHIJAAAA | mcp                 | 9.42         | minecraft.jar                             | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | voxelmap            | 1.9.25       | forgemod_VoxelMap-1.9.28_for_1.12.2.jar   | None                                     |
	| UCHIJAAAA | damageindicatorsmod | 1.0          | [1.12.2]DamageIndicatorsMod-3.5.1 (1).jar | None                                     |
	| UCHIJAAAA | gokistats           | 1.2.8.2      | gokiStats-1.2.8.2.jar                     | None                                     |
	| UCHIJAAAA | jei                 | 4.13.1.225   | jei_1.12.2-4.13.1.225.jar                 | None                                     |
	| UCHIJAAAA | mm                  | 0.4          | Maelstrom+Mod-0.4 (2).jar                 | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Garam1207'/716, l='새로운 세계', x=327.70, y=10.00, z=287.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by miyo6032** [comment]
Will be fixed in the next patch
